### ISSUE TITLE
link

### ISSUE THREAD

**Issue by Butonix** [alexstep/ipfs-telegra.ph#1]
Hello
Why after the publication throws on the site
https://ipfs.io/ipfs/QmZqh2czC9uQJpRYHNU7GeuHkrYsMVGLvA3qLBhYZdAnJ4/
How to make sure that all articles are stored in my database and under my domain?

**Comment by alexstep** [comment]
All data save in IPFS - decentralised filesystem, without any domain or personal database.  And decentralisation - basic idea in  this service.  

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Butonix** [comment]
Is it possible to alter it to its database?
To save articles in your database
As a telegraph

**Comment by alexstep** [comment]
Hmm... yes, but for what?  I mean, you can use openoffice :)  or one of thousands other CMS.

This function https://github.com/alexstep/ipfs-telegra.ph/blob/master/public/js/core.js#L1305 call when user publish article.

**Comment by Butonix** [comment]
I can pay you, you can do?

**Comment by alexstep** [comment]
@Butonix No, I'm not interested

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Butonix** [comment]
Well then it's useless code
